Algoritmo "Terreno"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/03/2023
Var
   r:  inteiro
   area: real


   
Inicio
       escreval("Digite o valor do raio do circulo:")
       leia(r)

       
      area <-   r * r * pi
      escreval("Area = ", area:5:3)


Fimalgoritmo